### ISSUE TITLE
Synoloader does not 'connect' until a manual connection is made

### ISSUE THREAD

**Issue by hyraxxxx** [Lemutar/Synoloader#10]
Recently I started having an issue where, after loading Firefox (38.0.1 although it happened on slightly older builds also), Synloader doesn't appear to connect to the NAS. If I right-click and chose "Download with Synoloader" I receive the error "No connection". If I then go into the Synloader Firefox preferences within ~2 seconds the "Not Connected" within the preferences dialogue box will change to "Connected".

At this point I can exit out of the dialogue box, once again right-click, chose "Download with Synoloader" and as the connection to the NAS has previously been established, the magnet link is sent to the NAS.

This only started happening in the last few months however I have had a few changes on my NAS in that time so it isn't clear if this is a bug or something on my end. I have to repeat this everytime I open Firefox.

Any help would be much appreciated.

**Comment by noplanman** [comment]
Is this still a problem for you with the latest version?
Otherwise we can close this issue :blush:

**Comment by hyraxxxx** [comment]
No - things have been working well again for a while. Thank you very much.

**Comment by noplanman** [comment]
Great! Thanks for the feedback.
