### ISSUE TITLE
Additional feature: Download speed

### ISSUE THREAD

**Issue by s0rk** [Lemutar/Synoloader#15]
Thanks for a great add-on! 

Would it be possible to also show the current download speed for each download?

**Comment by Lemutar** [comment]
This should be no problem will add it in the next version

**Comment by s0rk** [comment]
Oh, that would be great. Thanks a lot!

**Comment by noplanman** [comment]
Has been added with #29.
Will be included in the next release! :smiley:

**Comment by noplanman** [comment]
Ok, 2.2.0 is released and has this included.

**Comment by s0rk** [comment]
Absolutely marvellous. Hats off and all that!
