### ISSUE TITLE
Synoloader cna't connect

### ISSUE THREAD

**Issue by decarvalhoaa** [Lemutar/Synoloader#18]
Hi,
I have installed the extension but didn't manage to get to connect to my nas. The nsa is running DSM 5.2-5592 Update 4 and my FF is Firefox ESR 38.2.1 (linux).

I connect to DSM using the URL https://mycloud:5001 without issues. I am using a similar extension in Chrome/Chromium and can access with my admin account without problems. What should be my settings in Synoloader?

Thanks for you help in advance

Cheers
-A

**Comment by Nico1375** [comment]
Hello, same problem here. Under chromium I use a similar extension with the exact same connection parameters and it works perfectly. But I'd rather use firefox...

**Comment by sjel** [comment]
Same here. Was working flawlessly for couple of months, now no longer connects. HTTP capture shows really strange thing - addon actually even does not attempt to connect to my Syno, but it rather connects to "https://ukc.synology.com/Serv.php" URL, gets a valid response and does not do anything else. 15-20 seconds later it indicates connection issue.

**Comment by noplanman** [comment]
When connecting to your DSM using `https://mycloud:5001`, the Synoloader settings would be as follows (having set the correct username and password also):
![synoloader-settings](https://cloud.githubusercontent.com/assets/9423417/12224723/8675f058-b7f8-11e5-8eff-3913a35c024d.jpg)

@sjel, what version of Firefox are you using? Am I right to assume you have the newest version of the Synoloader extension? Are you using QuickConnect?

**Comment by sjel** [comment]
@noplanman I was using 43.0.1 and when realized that addon does not work - updated to the latest one. It did not help, though.
For the connection details - i'm using plain http over port 5000.

**Comment by noplanman** [comment]
@sjel I just tried 43.0.4 with Synoloader 2.1.0 on Windows 7 and it didn't work either at first.
After setting the correct settings the check would fail, but after restarting Firefox it worked perfectly.
Maybe you can try that?

Or alternatively:
1. Remove the plugin
2. Restart Firefox
3. Install Synoloader addon
4. Restart Firefox
5. Set connection details
6. Restart Firefox
7. Hopefully it's working now?!

**Comment by sjel** [comment]
@noplanman this is not the first time addon stops working in my environment. In the past I was doing some actions like re-installing the addon and restarting firefox and eventually it started to work again. The most unpleasant thing about all this magic is that it eventually stops working without any visible reason or change.

Also note, that I'm not suing QuickConnect - I'm entering either DNS name of my Syno, or it's IP address - both does not work well. I can provide any debug info you need to make it working - I really like your addon.

**Comment by noplanman** [comment]
Hmm, very strange. What operating system are you on? I've never had the issues you're describing using Firefox for OSX.

Also, to reply to your previous observation regarding `https://ukc.synology.com/Serv.php`:
That used to be the URL that QuickConnect request could be make, to find out the IP of the Syno box, to initialise the connection. I think since Synology changed to `quickconnect.to`, it's not working any more. I've been looking around for an alternative but haven't found one yet. Since you're not using QuickConnect though, you can happily ignore this :blush:

**Comment by sjel** [comment]
It's Win7 x64. 

Yeah, I guessed that it is QuickConnect URL, though I was surprised to see that addon connects to it regardless of the input I put - would it be IP, or DNS name it always tries quickconnect here. I'll also try a wireshark capture as it also can show a bit more information than Firefox console - like, non-successful attempts to connect.

**Comment by noplanman** [comment]
The cleaner option would probably be to add an extra item to the drop down menu.
- HTTP
- HTTPS
- QuickConnect

@Lemutar, what do you think? Also, do you know if there is a working QuickConnect API out there we can switch to? I've had a look but couldn't find anything that works with the new `quickconnect.to` that Synology moved to.

**Comment by decarvalhoaa** [comment]
Hi Armando,

I managed to get it working with your instructions below. The key step 
is restarting FF after setting the connection details.

Cheers and thanks.
A
