### ISSUE TITLE
Synoloader stopped working after last update ?

### ISSUE THREAD

**Issue by mickyway** [Lemutar/Synoloader#20]
My Synoloader stopped working. Its not visible anymore on the top right. When going to options the "check connection" doesn't respond. I'm on Synology 6.1 Beta (it worked before).

**Comment by noplanman** [comment]
Thanks for reporting this, will have a look into it as soon as possible.

@Lemutar, just a heads up...

**Comment by noplanman** [comment]
@mickyway
For the time being I've uploaded my dev version 2.0 for you to use.

You can find it here:
https://github.com/noplanman/Synoloader/raw/dev-2.0/bin/Synoloader.xpi

Just download that file, drag and drop it into your Firefox window and install it.

Please let me know if this works for you, thanks!

**Comment by noplanman** [comment]
@mickyway 
Version 2.1.0 is on Mozilla Add-On repository now, give it a go and get back to us if it works for you now, thanks.

**Comment by mickyway** [comment]
I now can pass the connection test, but i can't see the Synoloader icon in the firefox top bar. Did i forgotten something during the install phase ? 
Thanks guys.

**Comment by noplanman** [comment]
Have you tried reinstalling?
Or maybe it's jumped back into the [customize screen](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars)?
