### ISSUE TITLE
Firefox 47 connection issue

### ISSUE THREAD

**Issue by pascalou95** [Lemutar/Synoloader#38]
Hi. With recent Firefox 47 update (Windows) it's necessary to re-enter username/password each time Firefox is restarted. Else, no connection occurs. If I roll-back to FF 46.0.1 everything works again ...

Edit : You are right Larryadd, click on "check connection " is sufficient.

**Comment by Larryadd** [comment]
Same problem here, for me, no need to re-enter user name and password, just clic on "check connection" and it's back againg (even if the check connection is not complete). less anoying but still, I hope it will be fixed, it's a great addon !
