### ISSUE TITLE
What are the user account requirements for this to work?

### ISSUE THREAD

**Issue by electricessence** [Lemutar/Synoloader#44]
I set up a specific account for download and gave it access to the Download Station.
But when I try the account, it fails.  It would be nice to see the 'debug info' or log of _why_ it failed.

**Comment by noplanman** [comment]
You can find the debug info in your browser console.

On a Mac, you can open it with `Command+Shift+J`.
Using the menu, you can find it at: `Tools->Web Developer->Browser Console`.
